services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-17-alpine}
    container_name: dev_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password_123}
      POSTGRES_DB: ${POSTGRES_DB:-dev_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-4-management}
    container_name: dev_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-dev_rabbit}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-dev_rabbit_pass_123}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"  # RabbitMQ management UI

  flower:
    image: mher/flower:${FLOWER_VERSION:-2.0}
    container_name: dev_flower
    command: ["celery", "flower", "--port=${FLOWER_PORT:-5555}", "--broker=amqp://${RABBITMQ_USER:-dev_rabbit}:${RABBITMQ_PASSWORD:-dev_rabbit_pass_123}@rabbitmq:${RABBITMQ_PORT:-5672}//"]
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
